### ISSUE TITLE
ada.awa profile in the argo editor

### ISSUE THREAD

**Issue by tonygair** [stcarrez/ada-awa#8]
I have added the awa profile into the argo editor and then restarted argo. When I went to create the models directory as per your video there was no datamodel stereo type. I've checked what I did is exactly the same as in your video and cannot figure out what went wrong.

**Comment by stcarrez** [comment]
Ah yes, each time I have to re-setup ArgoUML, I reach this kind of issue. Annoying...

I have this article which also describes this:

https://blog.vacs.fr/vacs/blogs/tagged.html?tag=UML

The issue is to re-start ArgoUML at different steps of the process :-)

1.  Select and add a directory that contains the UML profiles (Edit -> Settings -> Profile -> Add)
2. Verify that the new directory appears in the directory list in Edit -> Settings -> Profile -> Add dialog
3. Re-start Argo-UML
4. Go again in Edit -> Settings -> Profile -> Add
5. The directory you added should still be there in the Add dialog. You should see there (on the left) the Dynamo.xmi UML profile. Click on ">>" to activate it.
6. Re-start Argo-UML
7. At this step, you should see Dynamo.xmi in the ProfileConfiguration

Alternatively you can check the file `~/.argouml/argo.user.properties`, it should contain something like:


  argo.profiles.default=CUML 1.4*CGoodPractices*CCodeGeneration*Ufile\:/build/local-gnat-2019/share/dynamo/base/uml/Dynamo.xmi*
  argo.profiles.directories=/build/local-gnat-2019/share/dynamo/base/uml*

May be you can edit the ArgoUML configuration file manually and update/add the two above properties after updating your installation path.

>

**Comment by tonygair** [comment]
Thanks Stephane, I'll try that

**Comment by tonygair** [comment]
Ah Glory be! it worked thank you for spending the time to help me Stephane

**Comment by tonygair** [comment]
I'm at the stage now of pulling in the AWA User definition. When I go to take it from the Profile Configuration in the top left window there is a AWA.xml folder which when opened only reveals a Critics file and there is no AWA tree under it.

**Comment by stcarrez** [comment]
Not easy to tell you what's going wrong....  I give you several checks in the hope they will give us some clue.

1. Can you try to load ada-awa/awa/uml/awa.zargo in ArgoUML ?

You should be able to see everything. This is what I'm doing to edit the UML models of all components. If not, check that the Dynamo.xmi profile is still selected and that it contains:
- AWA -> Events -> Module_Def
- ADO -> DataModel
- ASF -> Parts

2. Can you check the AWA.xmi file that was installed?

If you have commit 984060a89270934920a75a8ca920994c65af0bf0 (Aug 1 2019),
The file should be 1376014 bytes and its MD5sum is

 e50a2472a773d1360516996cc3ed59c6
 
3. Check ArgoUML logs

ArgoUML produces some output logs that may give you some information.
In most cases, when ArgoUML does not display model elements, this is because some
XMI file was incorrect. It is then reported in the log.

When I launch ArgoUML, I have no ERROR and no WARNING, only INFO.
You should get the same.

**Comment by tonygair** [comment]
I tried one and I was able to load this into ArgoUML and I was able to locate and place the awa users model into the diagram.
[argouml.log](https://github.com/stcarrez/ada-awa/files/3537284/argouml.log) I removed the log then started up argouml to get a log just containing the problem (hopefully)  but it looks like it does not like the dynamo.xmi file
Is that a lot of errors for argouml ? is there a better uml editor for this?

**Comment by tonygair** [comment]
as extra information my setup puts the ada-awa git check out code in ~/tools/ada-ada and my install in ~/opt/ada-awa , may be this should be the same directory?

**Comment by stcarrez** [comment]
Tony, your setup looks reasonable. I also install in another directory.

Looking at your argouml.log, it looks like the root cause is from the UML 4 Default profile.

> 2019-08-24 15:29:41,093 ERROR: Failed to resolve http://argouml.org/profiles/uml14/default-uml14.xmi#-84-17--56-5-43645a83:11466542d86:-8000:000000000000087E (XmiReferenceResolverImpl.java:321)

The Dynamo.xmi refers to a UML type with ID -84-17--56-5-43645a83:11466542d86:-8000:000000000000087E.
This ID is defined in the UML 1.4 profile.

I've discovered that ArgoUML needs an Internet connection when it loads the UML profiles.
It will download them from http://argouml.org. This is not clear why.
Can you run the following command:

  wget -O default.xmi http://argouml.org/profiles/uml14/default-uml14.xmi

I suspect that the HTTP access failed. If it works, a grep of the ID should give you a `<UML:DataType`

I'm also looking for another UML tool but I've never found one that looks more usable then ArgoUML.

**Comment by stcarrez** [comment]
Tony, one thing you may try is add the UML 1.4 profile that comes with Dynamo in your ArgoUML setup.

1. Go in Edit -> Settings -> Profile -> Add as you did to add Dynamo.xmi profile
2. Remove the active UML 1.4 profile by using '<<' and add the UML 1.4 default profile which has your installation path by using '>>'
3. Save settings and re-start ArgoUML

At this step, when you go back in ArgoUML, you should get two UML 1.4 default profiles.

It seems that there are sill good news on ArgoUML since @linustolke has recently migrated the ArgoUML sources to GitHub and development is started again.
I was able to get the recent sources and build them. With some hope, I may fix some bugs there...

**Comment by linustolke** [comment]
Hello Stephane!
I am glad that you managed to build everything. I am still working with setting up the Jenkins for the gerrithub builds.
I hope you will be able to fix the problems and if the Jenkins is not set up when you push your changes, I will verify it myself.

**Comment by tonygair** [comment]
I cannot remove the default UML 1.4 , I tried editing the argo config file directly  and it still appears. Should I try building the new argo sources and work with that?

**Comment by stcarrez** [comment]
No, it will not help you. I can reproduce your behavior when I turn off my Internet connection.

Can you check that the wget command succeeds when you start ArgoUML?

**Comment by tonygair** [comment]
I noticed the wget saves it as default.xmi when its name is default-uml14.xmi, Since it seems to be looking for default-uml14.xmi , is there an error here? Looking at the logfile , this is failing.

When argo starts  up, the first problem -- instead of describing it I will put the logfile below! :)
[argouml.log](https://github.com/stcarrez/ada-awa/files/3539978/argouml.log)

**Comment by stcarrez** [comment]
It looks like the directory `/home/tony/opt/ada-awa/share/dynamo/base/uml` is missing some files.
You should find the following files in it:

```
total 1412
-rw-r--r-- 1 jenkins jenkins 1376014 Aug 25 19:12 AWA.xmi
-rw-r--r-- 1 jenkins jenkins   20439 Aug 25 17:17 default-uml14.xmi
-rw-r--r-- 1 jenkins jenkins   45348 Aug 25 17:17 Dynamo.xmi
```

default-uml14.xmi and Dynamo.xmi are installed by dynamo package.
Beware that if you run dynamo installation, you have to run again the AWA installation.
That is you can do:

```
cd dynamo
make install
cd ../awa
make install
```

I've seen that you are using ArgoUML 0.34. I'm using the 0.35 version but I don't think this is your issue.

There is an alternative to using UML with AWA. You can design your data model in YAML.
This is not visual but you can do the same things including getting access to AWA data models.
The YAML support is described in https://ada-ado.readthedocs.io/en/latest/ADO_Model/

**Comment by tonygair** [comment]
Thanks Stephane, I'll try that.

**Comment by tonygair** [comment]
Those files AWA.xmi, default-uml14.xmi and Dynamo.xmi I believe have always been there. The java looks for http://argouml.org/user-profiles/Dynamo.xmi instead of checking the directory added to Argo. I'm starting to suspect the AWA.xmi file refering the java to the wrong locations.

**Comment by tonygair** [comment]
I did a new install with what I now know and keeping as closely as I could to the detailed instructions in the documentation and now all is well. I think it was all down to me. heh, Thanks for your help Stephane
