### ISSUE TITLE
No macOS support?

### ISSUE THREAD

**Issue by timmyjose** [stcarrez/ada-awa#9]
It would be nice to have macOS support as well. Is it on the cards? If there is a list of things that need to be in order for macOS builds to go through fine, I would be glad (as would others I'm sure) to try and help out.

**Comment by stcarrez** [comment]
I was able to build Ada Utility Library on MacOS and did some support for it.
I've tried on MacOS 64-bit with GNAT-2019.

To be honest, I never tried to build the AWA application on MacOS.
If Ada Utility Library compiles, then it should be ok.

**Comment by stcarrez** [comment]
I was able to build most of the libraries by running:

```
./configure --disable-postgresql
```

The Ada EL and AWA fail to link due to the following error:
```
  "___emutls_get_address", referenced from:
      _el__contexts__tls__finalize__2 in libelada.a(el-contexts-tls.o)
      _el__contexts__tls__initialize__2 in libelada.a(el-contexts-tls.o)
      _el__contexts__tls__tls_contextDF__2 in libelada.a(el-contexts-tls.o)
      _el__contexts__tls___assign__2 in libelada.a(el-contexts-tls.o)
      _el__contexts__tls__tls_contextSI__2 in libelada.a(el-contexts-tls.o)
      _el__contexts__tls__tls_contextFD in libelada.a(el-contexts-tls.o)
      _el__contexts__tls__current in libelada.a(el-contexts-tls.o)
      ...
```

Despite this link error, I was able to run successfully the unit tests of Ada Util, Ada Wiki,
Ada Servlet, Ada Server Faces and Ada Database Objects (using SQLite).

The `___emutls_get_address` is probably an installation issue of my GNAT 2019 community edition.
I don't know how to solve it without breaking my XCode installation...

**Comment by timmyjose** [comment]
@stcarrez Thank you for trying it out! This has been most helpful.

Indeed, I did face link errors myself when I tried building the project locally (without the `--disable-postgresql` switch). 

I suppose I could work with SQLite just to get familiar with the ecosystem. Thanks!
